### PR TITLE
Fix unary reductions

### LINKED ISSUE #359: Wrong behavior in unary reductions with specified axis
Bug reported by @trxcllnt 

The following program:

```
import cunumeric as cn
b = cn.zeros((1, 3))
b[0,1] = 1
print(b.all(axis=0))
```

produces wrong results when running on CPUs:

```
[False False False]
```

and causes a misaligned access when running with GPUs:

```
Internal CUDA failure with error misaligned address (cudaErrorMisalignedAddress) in file cunumeric/unary/unary_red.cu at line 330
legion_python: /gpfs/fs1/mpapadakis/legate.core/install/include/core/cuda/cuda_help.h:56: void legate::cuda::check_cuda(cudaError_t, const char*, int): Assertion `false' failed.
Unregistering error handlers
Signal 6 received by node 0, process 13875 (thread 7f209afd9700) - obtaining backtrace
Signal 6 received by process 13875 (thread 7f209afd9700) at: stack trace: 26 frames
  [0] = /lib/x86_64-linux-gnu/libpthread.so.0(+0x12980) [0x7f8639505980]
  [1] = /lib/x86_64-linux-gnu/libc.so.6(gsignal+0xc7) [0x7f8637200fb7]
  [2] = /lib/x86_64-linux-gnu/libc.so.6(abort+0x141) [0x7f8637202921]
  [3] = /lib/x86_64-linux-gnu/libc.so.6(+0x3048a) [0x7f86371f248a]
  [4] = /lib/x86_64-linux-gnu/libc.so.6(+0x30502) [0x7f86371f2502]
  [5] = /gpfs/fs1/mpapadakis/legate.core/install/lib/libcunumeric.so(legate::cuda::check_cuda(cudaError, char const*, int)+0x80) [0x7f20543f4a45]
  [6] = /gpfs/fs1/mpapadakis/legate.core/install/lib/libcunumeric.so(cunumeric::UnaryRedImplBody<(cunumeric::VariantKind)2, (cunumeric::UnaryRedCode)1, (legate_core_type_code_t)11, 2>::operator()(Legion::ReductionAccessor<Legion::ProdReduction<double>, false, 2, long long, Realm::AffineAccessor<double, 2, long long>, false>, Legion::FieldAccessor<(legion_privilege_mode_t)1, double, 2, long long, Realm::AffineAccessor<double, 2, long long>, false>, Realm::Rect<2, long long> const&, cunumeric::Pitches<1, true> const&, int, unsigned long) const+0x25f) [0x7f205497830f]
  [7] = /gpfs/fs1/mpapadakis/legate.core/install/lib/libcunumeric.so(void cunumeric::UnaryRedImpl<(cunumeric::VariantKind)2, (cunumeric::UnaryRedCode)1>::operator()<(legate_core_type_code_t)11, 2, (void*)0>(cunumeric::UnaryRedArgs&) const+0x10d) [0x7f205495034b]
  [8] = /gpfs/fs1/mpapadakis/legate.core/install/lib/libcunumeric.so(decltype(auto) legate::inner_type_dispatch_fn<2>::operator()<cunumeric::UnaryRedImpl<(cunumeric::VariantKind)2, (cunumeric::UnaryRedCode)1>, cunumeric::UnaryRedArgs&>(legate_core_type_code_t, cunumeric::UnaryRedImpl<(cunumeric::VariantKind)2, (cunumeric::UnaryRedCode)1>, cunumeric::UnaryRedArgs&)+0x195) [0x7f2054949f7b]
  [9] = /gpfs/fs1/mpapadakis/legate.core/install/lib/libcunumeric.so(decltype(auto) legate::double_dispatch<cunumeric::UnaryRedImpl<(cunumeric::VariantKind)2, (cunumeric::UnaryRedCode)1>, cunumeric::UnaryRedArgs&>(int, legate_core_type_code_t, cunumeric::UnaryRedImpl<(cunumeric::VariantKind)2, (cunumeric::UnaryRedCode)1>, cunumeric::UnaryRedArgs&)+0x8c) [0x7f205494a43b]
  [10] = /gpfs/fs1/mpapadakis/legate.core/install/lib/libcunumeric.so(void cunumeric::UnaryRedDispatch<(cunumeric::VariantKind)2>::operator()<(cunumeric::UnaryRedCode)1, (void*)0>(cunumeric::UnaryRedArgs&) const+0x45) [0x7f205494a4e7]
  [11] = /gpfs/fs1/mpapadakis/legate.core/install/lib/libcunumeric.so(decltype(auto) cunumeric::op_dispatch<cunumeric::UnaryRedDispatch<(cunumeric::VariantKind)2>, cunumeric::UnaryRedArgs&>(cunumeric::UnaryRedCode, cunumeric::UnaryRedDispatch<(cunumeric::VariantKind)2>, cunumeric::UnaryRedArgs&)+0x54) [0x7f2054949af4]
  [12] = /gpfs/fs1/mpapadakis/legate.core/install/lib/libcunumeric.so(+0x3992752) [0x7f2054944752]
  [13] = /gpfs/fs1/mpapadakis/legate.core/install/lib/libcunumeric.so(cunumeric::UnaryRedTask::gpu_variant(legate::TaskContext&)+0x18) [0x7f2054922ff0]
```

### PR DESCRIPTION
**Pull request by magnatelee**
This PR to fix #359 and also make `count_nonzero` use the same template so that it can support `axis`.

### CODE REVIEW

**Comment by magnatelee** [comment]
cc @trxcllnt this PR might have some merge conflicts with your ongoing PR if you are working on the C++ code.

File: src/cunumeric/unary/unary_red.cc [hunk 1]
```diff
@@ -74,19 +61,6 @@ struct ArgRedImplBody<VariantKind::CPU, OP_CODE, CODE, DIM> {
...
-                  const Pitches<DIM - 1>& pitches,
-                  int collapsed_dim,
-                  size_t volume) const
-  {
-    for (size_t idx = 0; idx < volume; ++idx) {
-      auto point = pitches.unflatten(idx, rect.lo);
-      OP::template fold<true>(lhs[point], LHS(point[collapsed_dim], rhs[point]));
-    }
-  }
 };
```
Comment (manopapad) [inline src/cunumeric/unary/unary_red.cc:64]: It looks like `ArgRedImplBody` is no longer used, and can be removed from this file and `unary_red_template.inl`.

**Comment by ipdemes** [comment]
I know it wasn't in original tests, but could you, maybe, add tests for different array dimension from (up to LEGATE_MAX_DIM)?

File: src/cunumeric/unary/unary_red_util.h [hunk 2]
```diff
@@ -72,146 +74,192 @@ constexpr decltype(auto) op_dispatch(UnaryRedCode op_code, Functor f, Fnargs&&..
...
-    OP::template fold<EXCLUSIVE>(rhs1, rhs2);
+    return rhs;
   }
+
+  __CUDA_HD__ static VAL convert(const RHS& rhs) { return rhs; }
 };
 
 template <legate::LegateTypeCode TYPE_CODE>
 struct UnaryRedOp<UnaryRedCode::ARGMAX, TYPE_CODE> {
   static constexpr bool valid = true;
```
Comment (ipdemes) [inline src/cunumeric/unary/unary_red_util.h:245]: should you replace here `valid =true` with `static constexpr bool valid = TYPE_CODE != legate::LegateTypeCode::COMPLEX128_LT;`  as you did for other specializations? The same for `ARGMAX`

File: src/cunumeric/unary/unary_red.cc (hunk 1 above)
Comment (magnatelee) [reply src/cunumeric/unary/unary_red.cc]: 3f2769dd3e95aa4ad078d1a8c0db475038068f91

File: src/cunumeric/unary/unary_red_util.h (hunk 2 above)
Comment (magnatelee) [reply src/cunumeric/unary/unary_red_util.h]: 08fd23f7c909db55ed87d1d7a4977bfef2960dfc

**Comment by magnatelee** [comment]
> I know it wasn't in original tests, but could you, maybe, add tests for different array dimension from (up to LEGATE_MAX_DIM)?

dafa481fa4be22e44ebc251628d23f25b5922c82

File: cunumeric/array.py [hunk 3]
```diff
@@ -3486,13 +3481,14 @@ def _perform_unary_reduction(
...
         dtype=None,
-        dst=None,
+        out=None,
         keepdims=False,
         args=None,
-        check_types=True,
         initial=None,
         where=True,
     ):
+        where = convert_to_predicate_ndarray(where)
```
Comment (manopapad) [inline cunumeric/array.py:3490]: I assume this is only necessary because of the fallback from `ufunc.py`; all uses of this function in `array.py` and `module.py` are internal, and should have already converted their arguments.

In that case, can you use `@add_boilerplate` instead? That way we also handle `out` automatically.

File: cunumeric/array.py [hunk 4]
```diff
@@ -1574,8 +1571,7 @@ def argmax(self, axis=None, out=None):
             self,
             axis=axis,
             dtype=np.dtype(np.int64),
-            dst=out,
-            check_types=False,
+            out=out,
         )
```
Comment (manopapad) [inline cunumeric/array.py:1575]: Can you add the missing `@add_boilerplate` on argmax and argmin?

**Comment by manopapad** [comment]
This program:

```
import cunumeric as cn
print(cn.argmax(cn.ones((3,))))
```

is failing with:

```
Traceback (most recent call last):
  File "/Users/mpapadakis/legate.core/install/lib/python3.8/site-packages/legion_top.py", line 434, in legion_python_main
    run_path(args[start], run_name='__main__')
  File "/Users/mpapadakis/legate.core/install/lib/python3.8/site-packages/legion_top.py", line 255, in run_path
    exec(code, module.__dict__, module.__dict__)
  File "a.py", line 2, in <module>
    print(cn.argmax(cn.ones((3,))))
  File "/Users/mpapadakis/cunumeric/cunumeric/coverage.py", line 106, in wrapper
    return func(*args, **kwargs)
  File "/Users/mpapadakis/cunumeric/cunumeric/array.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/Users/mpapadakis/cunumeric/cunumeric/module.py", line 4447, in argmax
    return a.argmax(axis=axis, out=out)
  File "/Users/mpapadakis/cunumeric/cunumeric/coverage.py", line 106, in wrapper
    return func(*args, **kwargs)
  File "/Users/mpapadakis/cunumeric/cunumeric/array.py", line 1569, in argmax
    return self._perform_unary_reduction(
  File "/Users/mpapadakis/cunumeric/cunumeric/array.py", line 3558, in _perform_unary_reduction
    result._thunk.unary_reduction(
  File "/Users/mpapadakis/cunumeric/cunumeric/deferred.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/Users/mpapadakis/cunumeric/cunumeric/deferred.py", line 1703, in unary_reduction
    lhs_array.fill(np.array(fill_value, dtype=lhs_array.dtype))
OverflowError: Python int too large to convert to C long
```

and this:

```
import cunumeric as cn
print(cn.argmax(cn.array([1,2,3,1])))
```

is failing with:

```
Traceback (most recent call last):
  File "/Users/mpapadakis/legate.core/install/lib/python3.8/site-packages/legion_top.py", line 434, in legion_python_main
    run_path(args[start], run_name='__main__')
  File "/Users/mpapadakis/legate.core/install/lib/python3.8/site-packages/legion_top.py", line 255, in run_path
    exec(code, module.__dict__, module.__dict__)
  File "a.py", line 2, in <module>
    print(cn.argmax(cn.array([1,2,3,1])))
  File "/Users/mpapadakis/cunumeric/cunumeric/coverage.py", line 106, in wrapper
    return func(*args, **kwargs)
  File "/Users/mpapadakis/cunumeric/cunumeric/array.py", line 88, in wrapper
    return func(*args, **kwargs)
  File "/Users/mpapadakis/cunumeric/cunumeric/module.py", line 4447, in argmax
    return a.argmax(axis=axis, out=out)
  File "/Users/mpapadakis/cunumeric/cunumeric/coverage.py", line 106, in wrapper
    return func(*args, **kwargs)
  File "/Users/mpapadakis/cunumeric/cunumeric/array.py", line 1569, in argmax
    return self._perform_unary_reduction(
  File "/Users/mpapadakis/cunumeric/cunumeric/array.py", line 3558, in _perform_unary_reduction
    result._thunk.unary_reduction(
  File "/Users/mpapadakis/cunumeric/cunumeric/deferred.py", line 75, in wrapper
    return func(*args, **kwargs)
  File "/Users/mpapadakis/cunumeric/cunumeric/deferred.py", line 1703, in unary_reduction
    lhs_array.fill(np.array(fill_value, dtype=lhs_array.dtype))
  File "/Users/mpapadakis/cunumeric/cunumeric/deferred.py", line 1103, in fill
    assert numpy_array.size == 1
AssertionError
```

File: src/cunumeric/unary/scalar_unary_red_template.inl [hunk 5]
```diff
@@ -66,68 +66,6 @@ struct ScalarUnaryRedImpl {
...
-    bool dense = false;
-#endif
-
-    ScalarUnaryRedImplBody<KIND, UnaryRedCode::ANY, CODE, DIM>()(out, in, rect, pitches, dense);
-  }
-};
-
 template <VariantKind KIND>
 struct ScalarUnaryRedImpl<KIND, UnaryRedCode::CONTAINS> {
   template <LegateTypeCode CODE, int DIM>
```
Comment (manopapad) [inline src/cunumeric/unary/scalar_unary_red_template.inl:71]: Use `RHS` instead of `VAL` in this function too?

File: src/cunumeric/unary/scalar_unary_red.cc [hunk 6]
```diff
@@ -39,82 +39,18 @@ struct ScalarUnaryRedImplBody<VariantKind::CPU, OP_CODE, CODE, DIM> {
...
-  {
-    auto result = LG_OP::identity;
-    detail::logical_operator<OP>(result, in, rect, pitches, dense);
-    out.reduce(0, result);
-  }
-};
-
 template <LegateTypeCode CODE, int DIM>
 struct ScalarUnaryRedImplBody<VariantKind::CPU, UnaryRedCode::CONTAINS, CODE, DIM> {
   using OP    = UnaryRedOp<UnaryRedCode::SUM, LegateTypeCode::BOOL_LT>;
```
Comment (manopapad) [inline src/cunumeric/unary/scalar_unary_red.cc:56]: RHS -> VAL here as well?

**Comment by magnatelee** [comment]
@manopapad I think what you reported is a known issue: https://github.com/nv-legate/cunumeric/issues/87 argmin and argmax currently support only the cases where the output is at least 1-d and an axis is given. #346 is supposed to address it, so let's not fix it in this PR.

File: cunumeric/array.py (hunk 4 above)
Comment (magnatelee) [reply cunumeric/array.py:1576]: 0983a85268d3ec45a7907e04bd342e4c87611909

File: src/cunumeric/unary/scalar_unary_red_template.inl (hunk 5 above)
Comment (magnatelee) [reply src/cunumeric/unary/scalar_unary_red_template.inl:71]: 868b68b7adafeab1060ae5f3cffacb0b980207f2

File: cunumeric/array.py (hunk 3 above)
Comment (magnatelee) [reply cunumeric/array.py]: 0983a85268d3ec45a7907e04bd342e4c87611909

**Review by ipdemes — APPROVED** [review]

File: cunumeric/array.py [hunk 7]
```diff
@@ -3054,7 +3051,7 @@ def sum(
             UnaryRedCode.SUM,
```
Comment (manopapad) [inline cunumeric/array.py:3051]: The `dtype` argument of `sum` is not passed through.

File: cunumeric/array.py [hunk 8]
```diff
@@ -2781,7 +2778,7 @@ def prod(
             UnaryRedCode.PROD,
             self_array,
             axis=axis,
-            dst=out,
+            out=out,
             keepdims=keepdims,
             initial=initial,
             where=where,
```
Comment (manopapad) [inline cunumeric/array.py:2784]: The `dtype` argument of `prod` is not passed through.

File: cunumeric/array.py [hunk 9]
```diff
@@ -3516,121 +3512,63 @@ def _perform_unary_reduction(
...
-        if check_types and src.dtype != dst.dtype:
-            out_dtype = cls.find_common_type(src, dst)
-            if src.dtype != out_dtype:
-                temp = ndarray(
-                    src.shape,
-                    dtype=out_dtype,
-                    inputs=(src, where),
-                )
-                temp._thunk.convert(src._thunk)
-                src = temp
```
Comment (manopapad) [inline cunumeric/array.py:3595]: This logic is missing from the new version; if the calling code passes a `dtype` that is different form `src.dtype`, the thunk function will end up with `src.dtype != dst.dtype`, which it cannot handle.

Comment (magnatelee) [reply cunumeric/array.py:3595]: dbb22229a813684621c0d0228f9171120e576b0b

File: cunumeric/array.py (hunk 8 above)
Comment (magnatelee) [reply cunumeric/array.py:2785]: dbb22229a813684621c0d0228f9171120e576b0b

File: cunumeric/array.py (hunk 7 above)
Comment (magnatelee) [reply cunumeric/array.py:3052]: dbb22229a813684621c0d0228f9171120e576b0b

File: cunumeric/array.py [hunk 10]
```diff
@@ -3483,12 +3485,28 @@ def _perform_unary_reduction(
...
+            assert dtype is None
+            dtype = src.dtype
+        else:
+            # If 'dtype' exists, that determines both the accumulation dtype
+            # and the output dtype
+            if dtype is not None:
+                res_dtype = dtype
+            else:
+                dtype = src.dtype
+                res_dtype = src.dtype
```
Comment (manopapad) [inline cunumeric/array.py:3502]: According to the NumPy documentation on `reduce`:

```
dtypedata-type code, optional
The type used to represent the intermediate results. Defaults to the data-type of the output array if this is provided, or the data-type of the input array if no output array is provided.
```

this should do one more check:

```
elif out is not None:
  dtype = out.dtype
  res_dtype = out.dtype
else:
  dtype = src.dtype
  res_dtype = src.dtype
```

Comment (magnatelee) [reply cunumeric/array.py:3505]: c5d7f85afd505eeba09c2d65e1f7b05d16f104ef

File: cunumeric/array.py [hunk 11]
```diff
@@ -1559,24 +1559,21 @@ def argmax(self, axis=None, out=None):
...
-        if axis is None:
-            axis = self.ndim - 1
-        elif type(axis) != int:
-            raise TypeError("'axis' argument for argmax must be an 'int'")
-        elif axis < 0 or axis >= self.ndim:
-            raise TypeError("invalid 'axis' argument for argmax " + str(axis))
+        if out is not None and out.dtype != np.int64:
+            raise ValueError("output array must have int64 dtype")
+        if axis is not None and not isinstance(axis, int):
+            raise ValueError("axis must be an integer")
```
Comment (manopapad) [inline cunumeric/array.py:1565]: Do you need to check these here (and in argmin)? Aren't these taken care of by `_perform_unary_reduction`?

Comment (magnatelee) [reply cunumeric/array.py:1565]: `argmin` and `argmax` have a stronger requirement; they don't allow the `axis` to be a tuple. That's why this extra check is in place.

**Review by manopapad — APPROVED** [review]
